---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - git

- name: Get Django Repository
  # I think this will clone if it doesn't exist, then update otherwise.
  git: repo=git@github.com:Estmator/EstmatorApp.git dest={{ home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml


- name: Set DB URL
  set_fact: 
    db_url: "postgres://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Whats the DB URL
  debug: var=db_url

- name: Run Migrations
  environment:
    SECRET_KEY: "{{ secret_key }}"
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: estmator_project.settings
    command: migrate

- name: Collect Static Files
  environment:
    SECRET_KEY: "{{ secret_key }}"
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: estmator_project.settings
    command: collectstatic
