---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - git

- name: copy GitHub deploy keys
  copy: src=id_rsa dest=~/.ssh/id_rsa
  copy: src=id_rsa.pub dest=~/.ssh/id_rsa.pub

- name: Get Django Repository
  git: repo=git@github.com:Estmator/EstmatorApp.git
       dest={{ home }}
       force=yes
       key_file=~/.ssh/id_rsa

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ home }}/requirements.txt"

- name: Get Secrets
  include_vars: secrets.yml

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Set DB URL
  set_fact: 
    db_url: "postgres://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    SECRET_KEY: "{{ secret_key }}"
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: estmator_project.settings
    command: migrate

# only copy the base sql file, not automating loading this file
# loading can be destructive and wipes out existing data
- name: Copy Base SQL Data
  copy: src=basedb.json dest={{ django_home }}

- name: Collect Static Files
  environment:
    SECRET_KEY: "{{ secret_key }}"
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: estmator_project.settings
    command: collectstatic
